---
- name: Restart Skiff stack
  hosts: local
  become: true
  become_user: root
  tasks:

  - name: stop services
    service: name="{{item}}" state=stopped
    with_items:
      - pm2
      - nginx

  - name: start services
    service: name="{{item}}" state=started
    with_items:
      - pm2
      - nginx

